version: '3.7'
services:

  dashboard:
    build: 
      context: ./
    container_name: CEAA_Acciones_Desinfeccion_dashboard
    hostname: CEAA_Acciones_Desinfeccion_dashboard
    restart: always
    ports:
      - 8052:8052
    networks:
      - network 
    

      
networks:
  network:
    driver: bridge
